"""empty message

Revision ID: 31850461ed3
Revises: 365f1188e96
Create Date: 2016-02-12 23:50:58.951032

"""

# revision identifiers, used by Alembic.
revision = '31850461ed3'
down_revision = '365f1188e96'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_settings',
    sa.Column('application_settings_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('application_id', sa.String(length=64), nullable=False),
    sa.Column('settings', postgresql.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('application_settings_id')
    )
    op.create_index('idx_application_settings', 'application_settings', ['user_id', 'application_id'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_application_settings', table_name='application_settings')
    op.drop_table('application_settings')
    ### end Alembic commands ###
