"""empty message

Revision ID: 365f1188e96
Revises: 4ccccdd6b0
Create Date: 2015-12-04 15:51:49.247979

"""

# revision identifiers, used by Alembic.
revision = '365f1188e96'
down_revision = '4ccccdd6b0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_installation')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_installation',
    sa.Column('app_installation_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('app_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='app_installation_user_id_fkey'),
    sa.PrimaryKeyConstraint('app_installation_id', name='app_installation_pkey')
    )
    ### end Alembic commands ###
