"""empty message

Revision ID: 400aaaf88e5
Revises: 16709bf9085
Create Date: 2015-12-01 23:31:27.438694

"""

# revision identifiers, used by Alembic.
revision = '400aaaf88e5'
down_revision = '16709bf9085'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login', sa.String(length=32), nullable=False))
    op.create_index('idx_user_login', 'user', ['login'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_login', table_name='user')
    op.drop_column('user', 'login')
    ### end Alembic commands ###
