"""empty message

Revision ID: 813ee19614
Revises: 400aaaf88e5
Create Date: 2015-12-03 12:05:25.680915

"""

# revision identifiers, used by Alembic.
revision = '813ee19614'
down_revision = '400aaaf88e5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_installation',
    sa.Column('app_installation_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('app_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('app_installation_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_installation')
    ### end Alembic commands ###
